/**
 * Camp Doodle — Site Data
 * Edit puppies, parents, reels, and journey milestones here.
 * Photos go in assets/puppies/ — see paths below.
 */

window.CD = {

  /* ─── PUPPIES ──────────────────────────────────────────────────────────── */
  // status: 'available' | 'reserved' | 'pending' | 'keeper'
  puppies: [
    {
      id: 'coby-600',
      puppyId: '600',
      name: 'Coby',
      sex: 'Male',
      born: 'May 19, 2026',
      birthTime: '6:00 PM',
      breed: 'Goldendoodle',
      coat: 'Golden / Apricot',
      weight: null,
      personality: 'Coby is our firstborn boy and a spitting image of his dad. He has a soft golden/apricot coat, sweet teddy-bear face, and calm little look.',
      tags: ['calm', 'confident', 'gentle', 'affectionate'],
      status: 'available',
      photo: 'assets/puppies/coby-600.png',
      photoAlt: 'Coby, a male Goldendoodle puppy with a golden apricot coat and sweet teddy-bear face.',
      photoPosition: 'center top',
      photos: ['assets/puppies/coby-600.png'],
      video: null,
      readyDate: 'July 14, 2026',
      vaccineDate: 'June 26, 2026',
      nextBooster: 'July 17–24, 2026',
      notes: 'First puppy born.',
    },
    {
      id: 'nova-605',
      puppyId: '605',
      name: 'Nova',
      sex: 'Female',
      born: 'May 19, 2026',
      birthTime: '6:05 PM',
      breed: 'Goldendoodle',
      coat: 'Light Cream',
      weight: null,
      personality: 'Nova is a beautiful light cream female with gentle eyes, a soft teddy-bear face, and a bright little glow that makes her stand out.',
      tags: ['gentle', 'calm', 'affectionate', 'companion'],
      status: 'available',
      photo: 'assets/puppies/nova-605.png',
      photoAlt: 'Nova, a female Goldendoodle puppy with a light cream coat and gentle eyes.',
      photoPosition: 'center top',
      photos: ['assets/puppies/nova-605.png'],
      video: null,
      readyDate: 'July 14, 2026',
      vaccineDate: 'June 26, 2026',
      nextBooster: 'July 17–24, 2026',
      notes: null,
    },
    {
      id: 'maple-608',
      puppyId: '608',
      name: 'Maple',
      sex: 'Female',
      born: 'May 19, 2026',
      birthTime: '6:08 PM',
      breed: 'Goldendoodle',
      coat: 'Warm Golden / Apricot',
      weight: null,
      personality: 'Maple is a warm golden female with apricot coloring, sweet eyes, and a cozy cuddly look that fits perfectly in a family home.',
      tags: ['calm', 'gentle', 'affectionate', 'easygoing'],
      status: 'available',
      photo: 'assets/puppies/maple-608.png',
      photoAlt: 'Maple, a female Goldendoodle puppy with warm golden apricot coloring and a soft cuddly look.',
      photoPosition: 'center top',
      photos: ['assets/puppies/maple-608.png'],
      video: null,
      readyDate: 'July 14, 2026',
      vaccineDate: 'June 26, 2026',
      nextBooster: 'July 17–24, 2026',
      notes: null,
    },
    {
      id: 'lumi-610',
      puppyId: '610',
      name: 'Lumi',
      sex: 'Female',
      born: 'May 19, 2026',
      birthTime: '6:10 PM',
      breed: 'Goldendoodle',
      coat: 'Light Golden / Apricot',
      weight: null,
      personality: 'Lumi is a light golden female with a soft sunshine glow, fluffy coat, and sweet teddy-bear face.',
      tags: ['gentle', 'affectionate', 'calm', 'companion'],
      status: 'available',
      photo: 'assets/puppies/lumi-610.png',
      photoAlt: 'Lumi, a female Goldendoodle puppy with a light golden coat and a soft sunshine glow.',
      photoPosition: 'center top',
      photos: ['assets/puppies/lumi-610.png'],
      video: null,
      readyDate: 'July 14, 2026',
      vaccineDate: 'June 26, 2026',
      nextBooster: 'July 17–24, 2026',
      notes: null,
    },
    {
      id: 'elvis-630',
      puppyId: '630',
      name: 'Elvis',
      sex: 'Male',
      born: 'May 19, 2026',
      birthTime: '6:30 PM',
      breed: 'Goldendoodle',
      coat: 'Black with White Chest Patch',
      weight: null,
      personality: 'Elvis is a handsome black male with a small white chest patch and a sweet little face that makes him hard not to fall in love with. Possible keeper.',
      tags: ['playful', 'confident', 'social', 'affectionate'],
      status: 'keeper',
      photo: 'assets/puppies/elvis-630.png',
      photoAlt: 'Elvis, a male Goldendoodle puppy with a black coat and small white chest patch.',
      photoPosition: 'center top',
      photos: ['assets/puppies/elvis-630.png'],
      video: null,
      readyDate: 'July 14, 2026',
      vaccineDate: 'June 26, 2026',
      nextBooster: 'July 17–24, 2026',
      notes: 'Black coat with small white chest patch.',
    },
    {
      id: 'onyx-634',
      puppyId: '634',
      name: 'Onyx',
      sex: 'Male',
      born: 'May 19, 2026',
      birthTime: '6:34 PM',
      breed: 'Goldendoodle',
      coat: 'Black / Rich Dark',
      weight: null,
      personality: 'Onyx is a handsome black male with a rich dark coat, sweet eyes, and a soft teddy-bear look that makes him stand out.',
      tags: ['calm', 'confident', 'gentle', 'affectionate'],
      status: 'available',
      photo: 'assets/puppies/onyx-634.png',
      photoAlt: 'Onyx, a male Goldendoodle puppy with a rich black coat and soft teddy-bear look.',
      photoPosition: 'center top',
      photos: ['assets/puppies/onyx-634.png'],
      video: null,
      readyDate: 'July 14, 2026',
      vaccineDate: 'June 26, 2026',
      nextBooster: 'July 17–24, 2026',
      notes: null,
    },
    {
      id: 'finn-635',
      puppyId: '635',
      name: 'Finn',
      sex: 'Male',
      born: 'May 19, 2026',
      birthTime: '6:35 PM',
      breed: 'Goldendoodle',
      coat: 'Golden / Apricot',
      weight: null,
      personality: 'Finn is a handsome golden male with a beautiful apricot coat, sweet dark eyes, and a confident little stance.',
      tags: ['playful', 'confident', 'active', 'affectionate'],
      status: 'available',
      photo: 'assets/puppies/finn-635.png',
      photoAlt: 'Finn, a male Goldendoodle puppy with a golden apricot coat and confident stance.',
      photoPosition: 'center top',
      photos: ['assets/puppies/finn-635.png'],
      video: null,
      readyDate: 'July 14, 2026',
      vaccineDate: 'June 26, 2026',
      nextBooster: 'July 17–24, 2026',
      notes: null,
    },
  ],

  /* ─── PARENTS ──────────────────────────────────────────────────────────── */
  parents: [
    {
      id: 'copper',
      name: 'Copper',
      role: 'Dad',
      badge: 'Father',
      breed: 'Goldendoodle',
      traits: ['Loyal', 'Calm', 'Gentle'],
      story: 'Copper is the steady, golden heart of Camp Doodle. My best friend and baby boy — his quiet confidence, deep loyalty, and gentle soul pass beautifully to every single pup he fathers.',
      photo: 'assets/parents/copper_and_chloe.png',
    },
    {
      id: 'chloe',
      name: 'Chloe',
      role: 'Mom',
      badge: 'Mother',
      breed: 'Goldendoodle',
      traits: ['Nurturing', 'Sweet', 'Devoted'],
      story: 'Chloe is a devoted, fiercely loving mama. She keeps a close eye on every pup, settles the whelping box with her calm presence, and makes every person who meets her feel instantly at home.',
      photo: 'assets/parents/mom.png',
    },
    {
      id: 'piper',
      name: 'Piper',
      role: 'Aunt Piper',
      badge: 'Puppy Sitter',
      breed: 'Doodle Mix',
      traits: ['Gentle', 'Nurturing', 'Patient'],
      story: 'Piper is not a parent — she is something even sweeter. The self-appointed puppy sitter who checks on every litter, gently nudges the littlest ones, and keeps a watchful eye while Chloe rests. Every Camp Doodle puppy knows Aunt Piper.',
      photo: 'assets/parents/piper.jpg',
    },
  ],

  /* ─── VIDEO REELS ──────────────────────────────────────────────────────── */
  // Videos: place .mp4 files in assets/reels/
  // Posters: place thumbnail .jpg files in assets/reels/
  reels: [
    {
      id: 'reel-1',
      caption: 'Sleepy puppy pile',
      video: 'assets/reels/reel-sleepy.mp4',
      poster: 'assets/reels/reel-sleepy-poster.jpg',
    },
    {
      id: 'reel-2',
      caption: 'First tiny walks',
      video: 'assets/reels/reel-walks.mp4',
      poster: 'assets/reels/reel-walks-poster.jpg',
    },
    {
      id: 'reel-3',
      caption: 'Aunt Piper checking on everybody',
      video: 'assets/reels/reel-piper.mp4',
      poster: 'assets/reels/reel-piper-poster.jpg',
    },
    {
      id: 'reel-4',
      caption: 'Playtime starting',
      video: 'assets/reels/reel-playtime.mp4',
      poster: 'assets/reels/reel-playtime-poster.jpg',
    },
  ],

  /* ─── PUPPY JOURNEY TIMELINE ───────────────────────────────────────────── */
  journey: [
    {
      date: 'May 19',
      label: 'Born',
      note: 'Seven healthy puppies arrive safely into the world.',
      icon: '🐾',
    },
    {
      date: 'Week 1–2',
      label: 'Early Care',
      note: 'Around-the-clock monitoring, warmth, and time with mama.',
      icon: '🍼',
    },
    {
      date: 'Week 3',
      label: 'Daily Handling',
      note: 'Each puppy is gently handled every single day to build trust and calm.',
      icon: '🤲',
    },
    {
      date: 'Week 4–5',
      label: 'Socialization',
      note: 'Sounds, textures, gentle visitors, and first adventures outside.',
      icon: '🌱',
    },
    {
      date: 'Week 6',
      label: 'First Vet Check',
      note: 'Initial health exam and first deworming. Health records started.',
      icon: '🏥',
    },
    {
      date: 'June 26',
      label: 'First Vaccine',
      note: 'First 5-way puppy vaccine given. Puppy vaccine record started.',
      icon: '💉',
    },
    {
      date: 'July 14',
      label: 'Ready for Homes',
      note: 'Healthy, confident, and ready to join their forever family at 8 weeks.',
      icon: '🏡',
    },
  ],

};
